# PyTorch はじめの一歩

In [1]:
import torch

print("Is CUDA ready?", torch.cuda.is_available())

Is CUDA ready? True


In [2]:
# create a random array in CPU
x = torch.rand(3,3)
print(x)

tensor([[0.3052, 0.4440, 0.1633],
        [0.3029, 0.8292, 0.1728],
        [0.6852, 0.1654, 0.0479]])


In [3]:
# create another array in GPU device
y = torch.ones_like(x, device="cuda")
# move 'x' from CPU to GPU
x = x.to("cuda")

In [4]:
# run addition operation in GPU
z = x + y
print(z)

tensor([[1.3052, 1.4440, 1.1633],
        [1.3029, 1.8292, 1.1728],
        [1.6852, 1.1654, 1.0479]], device='cuda:0')


In [5]:
# move z from GPU to CPU
z = z.to("cpu")
print(z)

tensor([[1.3052, 1.4440, 1.1633],
        [1.3029, 1.8292, 1.1728],
        [1.6852, 1.1654, 1.0479]])


## ベンチマーキング (行列積)

In [11]:
s = 10000
device = "cpu"
x = torch.rand(s, s, device=device, dtype=torch.float32)
y = torch.rand(s, s, device=device, dtype=torch.float32)
%time z = torch.matmul(x,y)

CPU times: user 1min 31s, sys: 639 ms, total: 1min 32s
Wall time: 46.2 s


In [12]:
s = 10000
device = "cuda"
x = torch.rand(s, s, device=device, dtype=torch.float32)
y = torch.rand(s, s, device=device, dtype=torch.float32)
torch.cuda.synchronize()

%time z = torch.matmul(x,y); torch.cuda.synchronize()

CPU times: user 334 ms, sys: 220 ms, total: 554 ms
Wall time: 553 ms
